# Generated by Django 4.2.11 on 2025-03-31 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotels",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("availability", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "reservation_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("checkin", models.DateField()),
                ("checkout", models.DateField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_app.hotels",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("guest_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=20)),
                ("phoneNumber", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=200)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_app.reservation",
                    ),
                ),
            ],
        ),
    ]
