# Generated by Django 4.2.11 on 2025-04-01 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotels",
            old_name="availability",
            new_name="available",
        ),
    ]
