# Generated by Django 4.2.11 on 2025-04-07 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel_app", "0002_rename_availability_hotels_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="email",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="phoneNumber",
        ),
        migrations.RemoveField(
            model_name="hotels",
            name="email",
        ),
        migrations.RemoveField(
            model_name="hotels",
            name="phone",
        ),
    ]
