# Generated by Django 4.2.11 on 2025-04-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_remove_guest_email_remove_guest_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_number',
            field=models.CharField(default='TEMPCONFIRM123456', max_length=16),
        ),
    ]
